name: java-ci

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  init:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'adopt'

  build:
    runs-on: macos-latest
    needs: init

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build


  codecoverage:
    needs: [init, build]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: /src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco

  lint:
    runs-on: macos-latest
    needs: init

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: make lint